name = "messaging-app"
type = "javascript"
main = "src/index.js"
compatibility_date = "2025-05-23"

[durable_objects]
bindings = [
  { name = "CHATROOM", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

[site]
bucket = "./public"

[build]
command = ""

[env.production]
zone_id = ""  # optional, needed only if you're deploying to a custom domain
account_id = "your-account-id-here"
